import Groq from "groq-sdk";

export const options={
    method: 'GET',
    headers: {
      accept: 'application/json',
      Authorization: process.env.REACT_APP_TMDB_KEY
    }
  };

  // export const groq = new Groq({
  //   apiKey: process.env.REACT_APP_GROQ_KEY,
    
  //   dangerouslyAllowBrowser: true,
  // });

  export const ln = {
    en: {
      signUp: "Sign Up",
      search: "Search",
      placeHolder: "Enter movie name or details",
      signOut: "Sign Out",
      signIn: "Sign In",
      browse: "Browse",
      nowPlaying: "Now Playing",
      popularMovies: "Popular Movies",
      topRatedMovies: "Top Rated Movies",
      upcomingBollywood: "Upcoming Bollywood",
      discoverBollywood: "Discover Bollywood",
      popularTVShows: "Popular TV Shows",
      topRatedTVShows: "Top Rated TV Shows",
      popularIndianTVShows: "Popular Indian TV Shows",
      languages: {
        en: "English",
        hi: "Hindi",
        es: "Spanish",
        de: "German",
      },
      gpt: "GPT",
      movie: "Movie",
      overview: "Overview",
      play: "Play",
      moreInfo: "More Info",
      name: "Name",
      email: "Email",
      password: "Password",
      newToNetGPT: "New to NetGPT?",
      signUpNow: "Sign up now.",
      alreadyUser: "Already have an account?",
      signInNow: "Sign in now.",
      bot: "This page is protected by Google reCAPTCHA to ensure you’re not a bot.",
    },
  
    hi: {
      signUp: "साइन अप",
      search: "खोजें",
      placeHolder: "फिल्म का नाम या विवरण दर्ज करें",
      signOut: "साइन आउट",
      signIn: "साइन इन",
      browse: "ब्राउज़ करें",
      nowPlaying: "अभी चल रही फिल्में",
      popularMovies: "लोकप्रिय फिल्में",
      topRatedMovies: "शीर्ष रेटेड फिल्में",
      upcomingBollywood: "आने वाली बॉलीवुड फिल्में",
      discoverBollywood: "बॉलीवुड खोजें",
      popularTVShows: "लोकप्रिय टीवी शो",
      topRatedTVShows: "शीर्ष रेटेड टीवी शो",
      popularIndianTVShows: "लोकप्रिय भारतीय टीवी शो",
      languages: {
        en: "अंग्रेज़ी",
        hi: "हिंदी",
        es: "स्पैनिश",
        de: "जर्मन",
      },
      gpt: "जीपीटी",
      movie: "फिल्म",
      overview: "सारांश",
      play: "चलाएं",
      moreInfo: "अधिक जानकारी",
      name: "नाम",
      email: "ईमेल",
      password: "पासवर्ड",
      newToNetGPT: "NetGPT पर नए हैं?",
      signUpNow: "अभी साइन अप करें।",
      alreadyUser: "पहले से खाता है?",
      signInNow: "अभी साइन इन करें।",
      bot: "यह पृष्ठ Google reCAPTCHA द्वारा सुरक्षित है ताकि यह सुनिश्चित किया जा सके कि आप बॉट नहीं हैं।",
    },
  
    es: {
      signUp: "Regístrate",
      search: "Buscar",
      placeHolder: "Ingresa el nombre o los detalles de la película",
      signOut: "Cerrar sesión",
      signIn: "Iniciar sesión",
      browse: "Explorar",
      nowPlaying: "En cartelera",
      popularMovies: "Películas populares",
      topRatedMovies: "Películas mejor valoradas",
      upcomingBollywood: "Próximas películas de Bollywood",
      discoverBollywood: "Descubre Bollywood",
      popularTVShows: "Programas de TV populares",
      topRatedTVShows: "Programas de TV mejor valorados",
      popularIndianTVShows: "Programas de TV indios populares",
      languages: {
        en: "Inglés",
        hi: "Hindi",
        es: "Español",
        de: "Alemán",
      },
      gpt: "GPT",
      movie: "Película",
      overview: "Resumen",
      play: "Reproducir",
      moreInfo: "Más información",
      name: "Nombre",
      email: "Correo electrónico",
      password: "Contraseña",
      newToNetGPT: "¿Nuevo en NetGPT?",
      signUpNow: "Regístrate ahora.",
      alreadyUser: "¿Ya tienes una cuenta?",
      signInNow: "Inicia sesión ahora.",
      bot: "Esta página está protegida por Google reCAPTCHA para asegurarse de que no eres un bot.",
    },
  
    de: {
      signUp: "Registrieren",
      search: "Suchen",
      placeHolder: "Gib den Filmtitel oder Details ein",
      signOut: "Abmelden",
      signIn: "Anmelden",
      browse: "Durchsuchen",
      nowPlaying: "Jetzt im Kino",
      popularMovies: "Beliebte Filme",
      topRatedMovies: "Top-bewertete Filme",
      upcomingBollywood: "Kommende Bollywood-Filme",
      discoverBollywood: "Bollywood entdecken",
      popularTVShows: "Beliebte TV-Sendungen",
      topRatedTVShows: "Top-bewertete TV-Sendungen",
      popularIndianTVShows: "Beliebte indische TV-Sendungen",
      languages: {
        en: "Englisch",
        hi: "Hindi",
        es: "Spanisch",
        de: "Deutsch",
      },
      gpt: "GPT",
      movie: "Film",
      overview: "Übersicht",
      play: "Abspielen",
      moreInfo: "Mehr Infos",
      name: "Name",
      email: "E-Mail",
      password: "Passwort",
      newToNetGPT: "Neu bei NetGPT?",
      signUpNow: "Jetzt registrieren.",
      alreadyUser: "Bereits ein Konto?",
      signInNow: "Jetzt anmelden.",
      bot: "Diese Seite ist durch Google reCAPTCHA geschützt, um sicherzustellen, dass Sie kein Bot sind.",
    },
  };
  
  
    